=== jeg92-hub-1/sza/xml/erabiltzaileak.dtd
<?xml encoding="UTF-8"?>
<!ELEMENT erabiltzaileak (erabiltzailea)+>
<!ELEMENT erabiltzailea (izena,abizenak,eposta,pasahitza)>
<!ATTLIST erabiltzailea id ID #REQUIRED>
<!ELEMENT izena (#PCDATA)>
<!ELEMENT abizenak (#PCDATA)>
<!ELEMENT eposta (#PCDATA)>
<!ELEMENT pasahitza (#PCDATA)>

=== jeg92-hub-1/sza/xml/erabiltzaileak.xml
<?xml version="1.0" ?>
<!DOCTYPE erabiltzaileak SYSTEM "erabiltzaileak.dtd">
<erabiltzaileak>
	<erabiltzailea id="jegana016">
		<izena>Jon</izena>
		<abizenak>Egana Granado</abizenak>
		<eposta>jegana016@ikasle.ehu.eus</eposta>
		<pasahitza>asdf1234</pasahitza>
	</erabiltzailea>
	<erabiltzailea id="jesnaola010">
		<izena>Julen</izena>
		<abizenak>Esnaola Olano</abizenak>
		<eposta>jesnaola010@ikasle.ehu.eus</eposta>
		<pasahitza>1234asdf</pasahitza>
	</erabiltzailea>
</erabiltzaileak>
